export const DEFAULT_STORE = {
  store: {
    "document:document": {
      gridSize: 10,
      name: "",
      meta: {},
      id: "document:document",
      typeName: "document",
    },
    "page:page": {
      meta: {},
      id: "page:page",
      name: "Page 1",
      index: "a1",
      typeName: "page",
    },
    "shape:plLM5wdoyvhiAvVTJowtR": {
      x: 625,
      y: 289,
      rotation: 0,
      isLocked: false,
      opacity: 1,
      meta: {},
      id: "shape:plLM5wdoyvhiAvVTJowtR",
      type: "geo",
      props: {
        w: 274,
        h: 131,
        geo: "rectangle",
        color: "black",
        labelColor: "black",
        fill: "none",
        dash: "draw",
        size: "m",
        font: "draw",
        text: "",
        align: "middle",
        verticalAlign: "middle",
        growY: 0,
        url: "",
      },
      parentId: "page:page",
      index: "a1",
      typeName: "shape",
    },
    "shape:_yHR7LXyhmlLUslOH_VDP": {
      x: 1105,
      y: 508,
      rotation: 0,
      isLocked: false,
      opacity: 1,
      meta: {},
      id: "shape:_yHR7LXyhmlLUslOH_VDP",
      type: "geo",
      props: {
        w: 436,
        h: 217,
        geo: "rectangle",
        color: "yellow",
        labelColor: "black",
        fill: "none",
        dash: "draw",
        size: "m",
        font: "draw",
        text: "",
        align: "middle",
        verticalAlign: "middle",
        growY: 0,
        url: "",
      },
      parentId: "page:page",
      index: "a2",
      typeName: "shape",
    },
  },
  schema: {
    schemaVersion: 1,
    storeVersion: 4,
    recordVersions: {
      asset: {
        version: 1,
        subTypeKey: "type",
        subTypeVersions: {
          image: 3,
          video: 3,
          bookmark: 1,
        },
      },
      camera: {
        version: 1,
      },
      document: {
        version: 2,
      },
      instance: {
        version: 24,
      },
      instance_page_state: {
        version: 5,
      },
      page: {
        version: 1,
      },
      shape: {
        version: 3,
        subTypeKey: "type",
        subTypeVersions: {
          group: 0,
          text: 1,
          bookmark: 2,
          draw: 1,
          geo: 8,
          note: 5,
          line: 2,
          frame: 0,
          arrow: 3,
          highlight: 0,
          embed: 4,
          image: 3,
          video: 2,
          claim: 0,
          evidence: 0,
        },
      },
      instance_presence: {
        version: 5,
      },
      pointer: {
        version: 1,
      },
    },
  },
};
